# Generated by Django 3.1.14 on 2023-05-13 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0187_auto_20230417_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagoefectivo',
            name='oferta',
            field=models.FloatField(default=0.0),
        ),
    ]
