# Generated by Django 3.1.14 on 2023-05-13 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0188_pagoefectivo_oferta'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='descuento',
            field=models.FloatField(default=0.0),
        ),
    ]
