# Generated by Django 3.1.14 on 2023-07-14 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0190_proveedor_pendiente_rechazo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medalla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('descripcion', models.CharField(max_length=255, null=True)),
                ('imagen', models.ImageField(blank=True, upload_to='insignias')),
                ('estado', models.BooleanField(default=True)),
                ('tiempo', models.PositiveIntegerField(default=0)),
                ('valor', models.PositiveIntegerField(default=0)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('puntos', models.PositiveIntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='proveedor_pendiente',
            name='rechazo',
        ),
        migrations.AddField(
            model_name='datos',
            name='dinero_invertido',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='datos',
            name='tramites',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.CreateModel(
            name='clientexmedalla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoUsuario', models.BooleanField(default=True)),
                ('medalla', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.medalla')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
