# Generated by Django 3.1.14 on 2023-07-14 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0191_auto_20230714_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor_pendiente',
            name='rechazo',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
