# Generated by Django 3.1.14 on 2023-07-15 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0192_proveedor_pendiente_rechazo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medalla',
            name='puntos',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
