# Generated by Django 3.1.14 on 2023-09-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0193_auto_20230715_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos',
            name='descuento',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
