# Generated by Django 3.1.14 on 2024-03-08 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0194_datos_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='fecha_caducidad',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
