# Generated by Django 3.1.14 on 2024-06-18 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0195_proveedor_fecha_caducidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagoefectivo',
            name='solicitud',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.solicitud'),
        ),
        migrations.AddField(
            model_name='pagotarjeta',
            name='solicitud',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.solicitud'),
        ),
    ]
