# Generated by Django 3.1.14 on 2024-11-03 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0196_auto_20240618_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificacionmasiva',
            old_name='mensaje',
            new_name='nombre',
        ),
        migrations.AddField(
            model_name='ciudad_disponible',
            name='ciudad',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cupon',
            name='participantes',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notificacionmasiva',
            name='fecha_expiracion',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='notificacionmasiva',
            name='fecha_iniciacion',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='notificacionmasiva',
            name='frecuencia',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notificacionmasiva',
            name='hora',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='notificacionmasiva',
            name='tipo_proveedores',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
