# Generated by Django 3.1.14 on 2024-11-04 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0197_auto_20241103_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='fecha_expiracion',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='fecha_iniciacion',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='frecuencia',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='hora',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='nombre',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='tipo_proveedores',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notificacionmasiva',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='descripcion',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
